/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generadorclaves;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Generador de Claves");
        jLAdvertencia.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTdigitos = new javax.swing.JTextField();
        jBgenerar = new javax.swing.JButton();
        jTnumeros = new javax.swing.JTextField();
        jTletras = new javax.swing.JTextField();
        jTclave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBlimpiar = new javax.swing.JButton();
        jLAdvertencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setBackground(new java.awt.Color(182, 243, 2));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Generador de Claves");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Número de Dígitos:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Número de Números:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Número de Letras:");

        jTdigitos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTdigitosKeyReleased(evt);
            }
        });

        jBgenerar.setText("Generar");
        jBgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgenerarActionPerformed(evt);
            }
        });

        jTnumeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTnumerosKeyReleased(evt);
            }
        });

        jTletras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTletrasKeyReleased(evt);
            }
        });

        jTclave.setBackground(java.awt.Color.gray);
        jTclave.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jTclave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTclave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTclave.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Por Arceu80");

        jBlimpiar.setText("Limpiar");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });

        jLAdvertencia.setForeground(new java.awt.Color(255, 51, 0));
        jLAdvertencia.setText("El tamaño máximo de la clave es de 10 digitos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addComponent(jBlimpiar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBgenerar)
                                        .addGap(27, 27, 27))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTdigitos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTnumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTletras, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLAdvertencia))
                                            .addComponent(jTclave, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel1)))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTdigitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTnumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jTclave, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTletras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLAdvertencia)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBgenerar)
                            .addComponent(jBlimpiar))
                        .addGap(0, 94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        jTdigitos.setText("");
        jTnumeros.setText("");
        jTletras.setText("");
        jTclave.setText("");

        if (!jTletras.isEnabled() || !jTnumeros.isEnabled()) {
            jTletras.setEnabled(true);
            jTnumeros.setEnabled(true);
        }
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgenerarActionPerformed

        String resultado = "";
        int digitos, numeros, letras;
        char letra;
        String minuscula;

        try {
            digitos = Integer.parseInt(jTdigitos.getText());
            numeros = Integer.parseInt(jTnumeros.getText());
            letras = Integer.parseInt(jTletras.getText());

            String[] clave = new String[digitos];

            if (numeros == 0) {
                //System.out.print((char)aleatorio(65,90));
                for (int i = 0; i < clave.length; i++) {
                    letra = (char) aleatorio(65, 90);
                    if (aleatorio(0, 1) == 0) {
                        minuscula = String.valueOf(letra);
                        clave[i] = minuscula.toLowerCase();
                    } else {
                        clave[i] = String.valueOf(letra);
                    }

                }
            } else if (letras == 0) {
                for (int i = 0; i < clave.length; i++) {
                    clave[i] = String.valueOf(aleatorio(0, 9));
                }
            } else {

                int[] num = new int[numeros];
                char[] ch = new char[letras];

                for (int i = 0; i < num.length; i++) {
                    num[i] = aleatorio(0, 9);
                }

                for (int i = 0; i < ch.length; i++) {
                    ch[i] = (char) aleatorio(65, 90);
                }

                ArrayList<String> inter = new ArrayList();

                for (int i = 0; i < num.length; i++) {
                    inter.add(String.valueOf(num[i]));
                }

                for (int i = 0; i < ch.length; i++) {

                    if (aleatorio(0, 1) == 0) {
                        inter.add(String.valueOf(ch[i]));
                    } else {
                        inter.add(String.valueOf(ch[i]).toLowerCase());
                    }

                }

                Collections.shuffle(inter);

                for (int i = 0; i < inter.size(); i++) {
                    clave[i] = inter.get(i);
                }

                /*
                for (int i = 0; i < clave.length; i++) {
                    if (aleatorio(0, 1) == 0) {
                        letra = (char) aleatorio(65, 90);
                        if (aleatorio(0, 1) == 0) {
                            minuscula = String.valueOf(letra);
                            clave[i] = minuscula.toLowerCase();
                        } else {
                            clave[i] = String.valueOf(letra);
                        }
                    } else {
                        clave[i] = String.valueOf(aleatorio(0, 9));
                    }

                }*/
            }

            //jTclave.setText(digitos + ", " + numeros + ", " + letras);
            for (int i = 0; i < clave.length; i++) {
                resultado += clave[i];
            }
            System.out.println(resultado);
            jTclave.setText(resultado);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error, el valor introducido no es un numero", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jBgenerarActionPerformed

    private void jTnumerosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnumerosKeyReleased
        if (!jTnumeros.getText().equalsIgnoreCase("")) {
            if (Integer.parseInt(jTnumeros.getText()) == 0) {
                jTletras.setEnabled(false);
                jTletras.setText(jTdigitos.getText());
            } else if (Integer.parseInt(jTnumeros.getText()) > 0) {
                jTletras.setText(String.valueOf(Integer.parseInt(jTdigitos.getText()) - Integer.parseInt(jTnumeros.getText())));
            } else {
                jTletras.setEnabled(true);
            }
        } else {
            jTletras.setText("");
            jTletras.setEnabled(true);
        }

    }//GEN-LAST:event_jTnumerosKeyReleased

    private void jTletrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTletrasKeyReleased
        if (!jTletras.getText().equalsIgnoreCase("")) {
            if (Integer.parseInt(jTletras.getText()) == 0) {
                jTnumeros.setEnabled(false);
                jTnumeros.setText(jTdigitos.getText());
            } else if (Integer.parseInt(jTletras.getText()) > 0) {
                jTnumeros.setText(String.valueOf(Integer.parseInt(jTdigitos.getText()) - Integer.parseInt(jTletras.getText())));
            } else {
                jTnumeros.setEnabled(true);
            }
        } else {
            jTnumeros.setText("");
            jTnumeros.setEnabled(true);
        }

    }//GEN-LAST:event_jTletrasKeyReleased

    private void jTdigitosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdigitosKeyReleased
        if (!jTdigitos.getText().equalsIgnoreCase("")) {
            if (Integer.parseInt(jTdigitos.getText()) > 10) {
                jLAdvertencia.setVisible(true);
                jBgenerar.setEnabled(false);
            } else {
                jLAdvertencia.setVisible(false);
                jBgenerar.setEnabled(true);
            }
        }

    }//GEN-LAST:event_jTdigitosKeyReleased

    public int aleatorio(int min, int max) {
        double alea;
        int alea2;

        alea = Math.random();

        alea *= max - min + 1;

        alea += min;

        alea = Math.floor(alea);

        alea2 = (int) alea;

        return alea2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBgenerar;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JLabel jLAdvertencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTclave;
    private javax.swing.JTextField jTdigitos;
    private javax.swing.JTextField jTletras;
    private javax.swing.JTextField jTnumeros;
    // End of variables declaration//GEN-END:variables
}
